adding s3 extensions
opendatadiscovery/opendatadiscovery-specification pull request #37
Opened 2022-02-18 13:37 UTC by HaykManukyanAvetiky

coming with new s3 adapter I have add s3 extensions as well

2022-02-21 09:28 UTC, germanosin requested changes

2022-02-21 09:28 UTC, germanosin commented on specification/extensions/s3.json
> +                "Files": {
please use lowercase fieldnames

2022-02-21 09:28 UTC, germanosin commented on specification/extensions/s3.json
> +                "Avg. file size": {
please use camelCase in case of multiple words

2022-02-22 11:05 UTC, germanosin requested changes

2022-02-22 11:05 UTC, germanosin commented on specification/extensions/s3.json
> +                    "type": "string"
could we use enum here?

2022-02-23 07:54 UTC, HaykManukyanAvetiky commented on specification/extensions/s3.json
> +                    "type": "string"
done , pls check

2023-03-07 11:49 UTC, closed without merging